# Generated by Django 2.2.2 on 2019-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('CSE', 'Computer Science'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics and Communication'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], max_length=10)),
            ],
        ),
    ]
