# Generated by Django 2.2.2 on 2019-06-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20190613_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
    ]
