# Generated by Django 2.2.2 on 2019-06-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
